---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfrouting/cf-routing-webdriver

inputs:
  - name: istio-release
  - name: istio-scaling
  - name: deployments-repo

run:
  path: istio-release/ci/tasks/run-istio-scaling/task

params:
  DEPLOYMENT_NAME:
  VARS_LOCATION:
  SYSTEM_DOMAIN:
  NUMBER_OF_APPS:
  PASSING_THRESHOLD:
  CLEANUP_ORG:
  APP_MEM_SIZE: 16M
